name: Lint teams

on:
  push:
    branches-ignore:
      - main
    paths:
      - '.nais/teams.yaml'
      - '.github/workflows/linting.yaml'

jobs:
  lint-teams:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run yq .nais/teams.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq .nais/teams.yaml
